language: python
python:
  - "2.7"
#  - "3.3"
#  - "3.4"
notifications:
  email: false
install:
    - "pip install pep8 pylint"
script:
  - "pylint --disable=W0311,C0301 bamliquidator_internal/"
  #  - "pep8 --ignore=E501 ."
